### ISSUE TITLE
EN datatset

### ISSUE THREAD

**Issue by aesuli** [charlesmalafosse/open-dataset-for-sentiment-analysis#1]
Hi Charles,

is it possible for you to add one of the English datasets?

I would like to test it with your script from the other repo https://github.com/charlesmalafosse/FastText-sentiment-analysis-for-tweets

Thanks, Andrea.

**Comment by charlesmalafosse** [comment]
Hi Andrea,

Sure. I have added the rest of the datasets. Only thing is that they are in multiple files. Github limits the size of single files to 25mb. I have used 7zip to split the zip files. I hope it's not too complex to use them.

Charles

**Comment by aesuli** [comment]
Thank you Charles!
I reconstructed (on linux with 'cat file-split.zip.0* > file.zip') and decompressed the archives, everything is fine.
Andrea
