### ISSUE TITLE
How to reference your work

### ISSUE THREAD

**Issue by Oliph** [charlesmalafosse/open-dataset-for-sentiment-analysis#2]
Do you have any specific reference to cite your work in case it is used in scientific publication?

**Comment by charlesmalafosse** [comment]
Hi Olivier. You can use the following:
Malafosse Charles, Open Dataset For Sentiment Analysis, (2019), GitHub repository, https://github.com/charlesmalafosse/open-dataset-for-sentiment-analysis
Thanks for reaching out.
